name: Build Quite OK Audio

on:
  push:
    branches:
      - master

jobs:
  build:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        include:
          - os: windows-11-arm
            ARTIFACT_PREFIX: winarm64
            MSYS2_SYS: CLANGARM64
          - os: windows-latest
            ARTIFACT_PREFIX: win64
            MSYS2_SYS: UCRT64
    steps:
      - name: 'Configure git: core.autocrlf, core.eol'
        shell: pwsh
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v5
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.MSYS2_SYS}}
          update: true
          pacboy: toolchain:p
      - name: Build qoaconv
        run: |
          if [ "$MSYSTEM" = "CLANGARM64" ]; then
              clang qoaconv.c -std=gnu99 -lm -O3 -o qoaconv.exe
          elif [ "$MSYSTEM" = "UCRT64" ]; then
              gcc qoaconv.c -std=gnu99 -lm -O3 -o qoaconv.exe
          fi
      - name: Copy files
        shell: msys2 {0}
        run: |
          mkdir upload
          cp LICENSE upload/license.txt
          cp qoaconv.exe upload
          strip upload/*.exe
      - name: Upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: qoaconv-git-${{matrix.ARTIFACT_PREFIX}}-${{github.sha}}
          path: upload
          if-no-files-found: error
